version: '3.8'
services:
  backend:
    image: nest-post-master-node
    ports:
      - '3030:3000'
    links:
      - 'postgres:db'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/post-master-db

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
